server:
  port: 18081
spring:
  jackson:
    time-zone: GMT+8
  datasource:
    druid:
      db-type: mysql
      driver-class-name: com.mysql.cj.jdbc.Driver
      url: jdbc:mysql://127.0.0.1:3306/DEVICE?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
#      url: jdbc:mysql://47.93.30.9:3306/DEVICE?useUnicode=true&characterEncoding=UTF-8&useSSL=false&serverTimezone=GMT%2b8
      username: spider
      password: Spider#3340
      # 连接池的配置信息
      # 初始化大小，最小，最大
      initial-size: 2
      min-idle: 2
      max-active: 10
      # 配置获取连接等待超时的时间
      max-wait: 60000
      # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      timeBetweenEvictionRunsMillis: 60000
      # 配置一个连接在池中最小生存的时间，单位是毫秒
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1 FROM DUAL
      testWhileIdle: true
      test-on-borrow: false
      testOnReturn: false
      # 打开PSCache，并且指定每个连接上PSCache的大小
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙(关闭wall)
      filters: stat,wall,log4j2
      # 通过connectProperties属性来打开mergeSql功能；慢SQL记录
      connectionProperties: druid.stat.mergeSql\=true;druid.stat.slowSqlMillis\=5000
      # 配置DruidStatFilter
      web-stat-filter:
        enabled: true
        url-pattern: /*
        exclusions: "*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico,/druid/*"
      # 配置DruidStatViewServlet
      #是否启用StatViewServlet（监控页面）默认值为false（考虑到安全问题默认并未启动，如需启用建议设置密码或白名单以保障安全）
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        # IP白名单(没有配置或者为空，则允许所有访问)
        allow: 127.0.0.1,47.93.30.9
        # IP黑名单 (存在共同时，deny优先于allow)
        deny: 47.93.30.9
        #  禁用HTML页面上的“Reset All”功能
        reset-enable: false
        # 登录名
        login-username: admin
        # 登录密码
        login-password: 123456
  #redis集群
#  redis:
#    #host: 127.0.0.1
#    host: 47.93.30.9
#    port: 6379
#    timeout: 30000
#      #    集群环境打开下面注释，单机不需要打开
#      #    cluster:
#      #      集群信息
#      #      nodes: xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx,xxx.xxx.xxx.xxx:xxxx
#      #      #默认值是5 一般当此值设置过大时，容易报：Too many Cluster redirections
#      #      maxRedirects: 3
#    lettuce:
#      pool:
#        # 连接池中的最大空闲连接 默认8
#        max-active: 8
#        # 连接池中的最小空闲连接 默认0
#        min-idle: 0
#        # 连接池最大连接数 默认8 ，负数表示没有限制
#        max-idle: 8
#        # 连接池最大阻塞等待时间（使用负值表示没有限制） 默认-1
#        max-wait: -1
#    password:
#    application:
#      name: spring-boot-redis

mybatis:
  mapper-locations: classpath:mapper/*Mapper.xml
  type-aliases-package: com.hsmy.datastatistics.pojo

#配置日志信息
logging:
  config: classpath:config/log/logback.xml
  path: /home/log/18081
#  path: /Users/eipwork/Documents
  level:
    root: error
filepath:
#  his_path: /Users/eipwork/files/
  his_path: /data/backup/history/